name: Publish NuGet Package

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.ء'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Pack
        run: dotnet pack ./KZ.FileHash/KZ.FileHash.csproj --configuration Release --no-build --output ./artifacts

      #- name: NuGet login
      #  uses: NuGet/login@v1
      #  id: login
      #  with:
      #    user: ${{ secrets.NUGET_USER }}

      #- name: Push package
      #  run: >
      #    dotnet nuget push
      #    ./artifacts/KZ.FileHash.*.nupkg
      #    --api-key ${{ steps.login.outputs.NUGET_API_KEY }}
      #    --source https://api.nuget.org/v3/index.json
      #    --skip-duplicate
