using KZ.FileHash.Enums;
using System.Security.Cryptography;

namespace KZ.FileHash.Helpers
{
    /// <summary>
    /// Provides helper methods for working with supported hash algorithms.
    /// </summary>
    public static class AlgorithmsHelper
    {
        /// <summary>
        /// Gets the length of the hexadecimal string generated by the specified hash algorithm.
        /// </summary>
        /// <param name="algorithm">
        /// The hash algorithm used to generate the hexadecimal string.
        /// </param>
        /// <returns>
        /// The length of the hexadecimal hash string generated by the specified algorithm,
        /// or 0 if the algorithm is not supported.
        /// </returns>
        public static int GetAlgorithmHexStringLength(HashAlgorithmType algorithm)
        {
            return algorithm switch
            {
                HashAlgorithmType.MD5 => 32,
                HashAlgorithmType.SHA1 => 40,
                HashAlgorithmType.SHA256 or HashAlgorithmType.SHA3_256 => 64,
                HashAlgorithmType.SHA384 or HashAlgorithmType.SHA3_384 => 96,
                HashAlgorithmType.SHA512 or HashAlgorithmType.SHA3_512 => 128,
                _ => 0
            };
        }
        /// <summary>
        /// Gets the hash algorithms that generate hexadecimal strings of the specified length.
        /// </summary>
        /// <param name="length">
        /// The hexadecimal string length.
        /// Supported lengths are 32, 40, 64, 96, and 128.
        /// </param>
        /// <returns>
        /// An array containing the hash algorithms that generate hexadecimal strings
        /// of the specified length, or an empty array if no supported algorithm
        /// produces a hexadecimal string of that length.
        /// </returns>
        public static HashAlgorithmType[] GetAlgorithmsByLength(int length)
        {
            return length switch
            {
                32 => [HashAlgorithmType.MD5],
                40 => [HashAlgorithmType.SHA1],
                64 => [HashAlgorithmType.SHA256, HashAlgorithmType.SHA3_256],
                96 => [HashAlgorithmType.SHA384, HashAlgorithmType.SHA3_384],
                128 => [HashAlgorithmType.SHA512, HashAlgorithmType.SHA3_512],
                _ => []
            };
        }
        ///<summary>
        /// Gets the <see cref="HashAlgorithmName"/> associated with the specified hash algorithm.
        /// </summary>
        /// <param name="algorithm">
        /// A single supported hash algorithm. Composite values containing multiple
        /// algorithms are not supported by this method.
        /// <see cref="HashAlgorithmName"/>.
        /// </param>
        /// <returns>
        /// The <see cref="HashAlgorithmName"/> associated with the specified algorithm.
        /// </returns>
        /// <exception cref="ArgumentException">
        /// Thrown when <paramref name="algorithm"/> is <see cref="HashAlgorithmType.None"/>.
        /// </exception>
        /// <exception cref="ArgumentOutOfRangeException">
        /// Thrown when <paramref name="algorithm"/> contains an unsupported value.
        /// </exception>
        public static HashAlgorithmName GetAlgorithmName(HashAlgorithmType algorithm)
        {
            return algorithm switch
            {
                HashAlgorithmType.MD5 => HashAlgorithmName.MD5,
                HashAlgorithmType.SHA1 => HashAlgorithmName.SHA1,
                HashAlgorithmType.SHA256 => HashAlgorithmName.SHA256,
                HashAlgorithmType.SHA384 => HashAlgorithmName.SHA384,
                HashAlgorithmType.SHA512 => HashAlgorithmName.SHA512,
                HashAlgorithmType.SHA3_256 => HashAlgorithmName.SHA3_256,
                HashAlgorithmType.SHA3_384 => HashAlgorithmName.SHA3_384,
                HashAlgorithmType.SHA3_512 => HashAlgorithmName.SHA3_512,
                HashAlgorithmType.None => throw new ArgumentException("A hashing algorithm must be selected.", nameof(algorithm)),
                _ => throw new ArgumentOutOfRangeException(nameof(algorithm), algorithm, "The specified hash algorithm is not supported.")
            };
        }
    }
}
